### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by Eyesonly88** [Annihil/react-native-log-ios#2]
It doesn't work. I don't see any logs.

I just get:

```
React Native iOS Logger started for XCode project [MyProjectName]
```

**To Reproduce**
1. install the package just like the docs say (`npm i -g ...`)
2. `react-native run-ios`
3. `react-native-log-ios MyProjectName`

**Expected behavior**
Logs to show ...

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14
 - latest available from npm
 - xCode 10.1
 - RN 57.1

**Comment by Eyesonly88** [comment]
@Annihil Any ideas why it's not working? btw, I have xCode closed when I run the commands above.

**Comment by Eyesonly88** [comment]
For anyone trying to get ios logs from terminal, this is how I ended up doing it:
`xcrun simctl spawn booted log stream --predicate 'processImagePath ENDSWITH "YOUR_APP_NAME" AND senderImagePath ENDSWITH "YOUR_APP_NAME"' --color always`

**Comment by Annihil** [comment]
Hi, `MyProjectName` needs to be your XCode project name, and it is also case sensitive.
Knowing this, can you try again?
Having XCode closed is fine.
Thanks

**Comment by Eyesonly88** [comment]
@Annihil Yes, I know and tried with case sensitive as well but no logs were displayed for me.
As mentioned, I use the above command line now and it works great.

**Comment by transitive-bullshit** [comment]
I'm getting native logs with both @Eyesonly88 solution as well as using `react-native run-ios MyProjectName`, but I'm not getting `console.log` results.

Any idea why this may be happening?

**Comment by Eyesonly88** [comment]
@transitive-bullshit console logs appear for me in the command I posted.

**Comment by wincjh** [comment]
any solutions? i am having same problem

**Comment by wincjh** [comment]
i cant see console logs even if i typed the command above :(  any solutions?

**Comment by laurent22** [comment]
I think the usage instructions are misleading. The "XCode Project Name" mentioned in the doc is neither the Xcode project name, nor the bundle name but (at least in my case), the **FacebookDisplayName** because that's the name that shows up in the log.

So if it doesn't work for you, look up the `FacebookDisplayName` key in Info.plist and try to use this.
